name: Sync and Rebase

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync with upstream
        run: |
          git remote add upstream git@github.com:storybookjs/storybook.git
          git fetch upstream
          git merge upstream/master
          git push
      - name: Rebase creevey branch
        run: |
          git checkout creevey
          git rebase master
          git push --force
